name: "CI/CD Request"
description: Pipeline change or improvement
title: "[CI/CD] "
labels: ["ci-cd", "devops"]
body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
    validations:
      required: true
  - type: textarea
    id: detail
    attributes:
      label: Technical details
    validations:
      required: false
