name: "Feature Request"
description: Propose a new feature or improvement
title: "[FEATURE] "
labels: ["feature", "enhancement"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context / Need
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ] AC1
        - [ ] AC2
    validations:
      required: false
