name: "🧹 Technical Debt"
description: Dette technique à corriger
title: "[DEBT] "
labels: ["technical-debt"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Quelle dette ? Pourquoi existe-t-elle ?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposition de résolution
    validations:
      required: false
