name: "Technical Debt"
description: Technical debt to address
title: "[DEBT] "
labels: ["technical-debt"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What debt? Why does it exist?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed resolution
    validations:
      required: false
