name: Lint

on:
  pull_request:
  push:
    branches: [$default-branch, integration]

jobs:
  lint:
    uses: NerionSoft/nerionsoft-cicd/.github/workflows/reusable-lint.yml@main
    with:
      run-actionlint: true
      run-yamllint: true
      run-markdownlint: true
      run-pin-check: true
      yamllint-file-or-dir: "."
      markdownlint-globs: "**/*.md"
      pin-check-allowlist: ""
    permissions:
      contents: read
