name: Lint

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  lint:
    uses: NerionSoft/nerionsoft-cicd/.github/workflows/reusable-gh-lint.yml@main
    # with:
    #   run-actionlint: true
    #   run-yamllint: true
    #   run-markdownlint: true
    #   run-pin-check: true
    #   yamllint-file-or-dir: "."
    #   markdownlint-globs: "**/*.md"
    #   pin-check-allowlist: "NerionSoft/nerionsoft-cicd"
    #   run-sonar: false
    #   sonar-project-key: ""
    #   sonar-project-name: ""
    # secrets:
    #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #   SONAR_ROOT_CERT: ${{ secrets.SONAR_ROOT_CERT }}
