name: Next.js CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  ci:
    uses: NerionSoft/nerionsoft-cicd/.github/workflows/reusable-nextjs-ci.yml@main
    # with:
    #   node-version: "24"
    #   run-lint: true
    #   run-format: true
    #   run-typecheck: true
    #   run-test: true
    #   run-build: true
    #   run-e2e: true
    #   run-sonar: false
    #   sonar-project-key: ""
    #   sonar-project-name: ""
    # secrets:
    #   CI_DATABASE_URL: ${{ secrets.CI_DATABASE_URL }}
    #   CI_BETTER_AUTH_SECRET: ${{ secrets.CI_BETTER_AUTH_SECRET }}
    #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #   SONAR_ROOT_CERT: ${{ secrets.SONAR_ROOT_CERT }}
